### ISSUE TITLE
systemd deployment fails due to the service registration check

### ISSUE THREAD

**Issue by rake5k** [acme-software/ansible-java-deployment#24]
Happening using:
- CentOS 7.0.1406
- Ansible 2.7.7
- Python 2.7.15+

```
TASK [ansible-java-deployment : Service - Check if registered in systemctl] *********************************************************************************************************************************************************************************************
fatal: [target-host]: FAILED! => {"changed": true, "cmd": ["systemctl", "list-unit-files", "|", "grep", "service-1"], "delta": "0:00:00.009730", "end": "2019-03-25 15:19:52.891454", "msg": "non-zero return code", "rc": 1, "start": "2019-03-25 15:19:52.881724", "stderr": "Invalid number of arguments.", "stderr_lines": ["Invalid number of arguments."], "stdout": "", "stdout_lines": []}
```

**Comment by rake5k** [comment]
Fun fact: if ssh into the target host and run `systemctl list-unit-files | grep service-1`, I get no error:

```sh
[me@target-host ~]$ systemctl list-unit-files | grep service-1
service-1.service                      enabled
```

I just created a PR which removes this failing service-registration-checking task from the role. I think this one is not very necessary since Ansible will tell the user anyways that the service is not existing. That again should (imho) lead the user to a check of the according service definition file.

Please tell me if my assumptions are wrong... I would do my best trying to fix it ;-)

BR chris

**Comment by eikek** [comment]
@frne friendly ping :)
