### ISSUE TITLE
Add backup dir

### ISSUE THREAD

**Issue by tobiaswaelti** [acme-software/ansible-java-deployment#4]
add a job to backup old log files per intance

**Comment by frne** [comment]
@tobiaswaelti added for milestone 0.2.0

**Comment by frne** [comment]
@tobiaswaelti @christianharke @eikek Is this one still valid / needed? Doing spring cleanup... ;)

**Comment by rake5k** [comment]
Afaik this is not needed anymore. Keeping the logs over multiple deployments (when stored outside the app directory) seems to suffice.
